In [6]:
# Import necessary libraries
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForTokenClassification
from bert_utils import load_data  # Assuming this contains useful functions

In [7]:
# Configuration
MODEL_NAME = "dbmdz/bert-large-cased-finetuned-conll03-english"  
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Convert text into BERT-compatible tokens.
# Load the pre-trained BERT model.
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForTokenClassification.from_pretrained(MODEL_NAME)
model.to(device)
model.eval()  # Set model to evaluation mode

print("BERT Model loaded successfully!")

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

BERT Model loaded successfully!

In [8]:
# Load the CSV file
CSV_FILE = "speeches_2022-2023.csv"
df = pd.read_csv(CSV_FILE)

# Check the structure of the data
df.head()

,file_id,speaker_name,speaker_party,speech_text,jaar,date,kamer,category,title,document_number,url,meta_url,vergadernummer
0,h-tk-20222023-46-10,De voorzitter,NaN,Ik constateer dat de leden van de fracties van...,2022-2023,2023-01-31,tk,handelingen,10 Stemming motie Ondersteuning Nederlandse de...,NaN,https://zoek.officielebekendmakingen.nl/h-tk-2...,https://zoek.officielebekendmakingen.nl/h-tk-2...,"nr. 46, item 10"
1,h-tk-20222023-68-1,De voorzitter,NaN,Ik open de vergadering van donderdag 30 maart ...,2022-2023,2023-03-30,tk,handelingen,1,NaN,https://zoek.officielebekendmakingen.nl/h-tk-2...,https://zoek.officielebekendmakingen.nl/h-tk-2...,"nr. 68, item 1"
2,h-tk-20222023-18-8,De voorzitter,NaN,Aan de orde is de voortzetting van de begrotin...,2022-2023,2022-11-03,tk,handelingen,8 Begroting Buitenlandse Handel en Ontwikkelin...,NaN,https://zoek.officielebekendmakingen.nl/h-tk-2...,https://zoek.officielebekendmakingen.nl/h-tk-2...,"nr. 18, item 8"
3,h-tk-20222023-18-8,De voorzitter,NaN,Dat gezegd hebbende zou ik graag de minister h...,2022-2023,2022-11-03,tk,handelingen,8 Begroting Buitenlandse Handel en Ontwikkelin...,NaN,https://zoek.officielebekendmakingen.nl/h-tk-2...,https://zoek.officielebekendmakingen.nl/h-tk-2...,"nr. 18, item 8"
4,h-tk-20222023-18-8,Minister Schreinemacher,NaN,"Dank u wel, voorzitter. Dank u wel voor het de...",2022-2023,2022-11-03,tk,handelingen,8 Begroting Buitenlandse Handel en Ontwikkelin...,NaN,https://zoek.officielebekendmakingen.nl/h-tk-2...,https://zoek.officielebekendmakingen.nl/h-tk-2...,"nr. 18, item 8"

In [18]:
# Select a small fraction of data for testing
TEST_FRACTION = 0.005  
df_sample = df.sample(frac=TEST_FRACTION, random_state=42)

print(f" Sampled {len(df_sample)} rows from the dataset.")

 Sampled 444 rows from the dataset.

In [19]:
# Function to split text into 512-token chunks with overlap
def split_into_chunks(text, max_tokens=512, overlap=200):
    """
    Splits a speech into 512-token chunks while ensuring each chunk is within BERT's token limit.
    """
    tokens = tokenizer.encode(text, truncation=False, add_special_tokens=False)  # Tokenize without truncation
    chunks = []
    
    if len(tokens) <= max_tokens:
        return [tokenizer.decode(tokens)]  # Convert back to text if it's within limit
    
    for i in range(0, len(tokens), max_tokens - overlap):
        chunk_tokens = tokens[i : i + max_tokens - 2]  # Reserve space for [CLS] and [SEP]
        
        # Convert tokens back to text
        chunk_text = tokenizer.decode(chunk_tokens, skip_special_tokens=True)
        chunks.append(chunk_text)

    return chunks

print("✅ Splitting function ready!")

✅ Splitting function ready!

In [21]:
from tqdm import tqdm  # Import progress bar module

# Apply the splitting function to the sampled dataframe
df_sample["speech_text_chunks"] = df_sample["speech_text"].apply(split_into_chunks)

# === FUNCTION: TRANSLATE TEXT FROM DUTCH TO ENGLISH (WITH CHUNK HANDLING) ===
def translate_text(text_chunks):
    """Translates a list of text chunks and joins them back together."""
    translated_chunks = []
    
    for chunk in tqdm(text_chunks, desc="Translating chunks", leave=False):  # Progress bar for chunk translation
        try:
            translated_chunk = GoogleTranslator(source="nl", target="en").translate(chunk)
            
            # Ensure translation is a string, otherwise use original text
            if translated_chunk is None:
                translated_chunk = chunk  # Fallback to original text
            
            translated_chunks.append(str(translated_chunk))  # Ensure all chunks are strings
        
        except Exception as e:
            print(f"Translation error: {e}")
            translated_chunks.append(str(chunk))  # Fallback: Keep original text as a string
    
    return " ".join(translated_chunks)  # Combine chunks back into one text

# Apply translation to the segmented speeches with a progress bar
tqdm.pandas(desc="Translating speeches")
df_sample["speech_text_translated"] = df_sample["speech_text_chunks"].progress_apply(translate_text)

print(f"✅ Translated segmented speeches and added new column `speech_text_translated`.")

# Display a few translated rows
df_sample[["speech_text", "speech_text_translated"]].head()

Translating speeches:   0%|                             | 0/444 [00:00<?, ?it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.67it/s]
Translating speeches:   0%|                     | 2/444 [00:00<00:47,  9.24it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.30it/s]
Translating speeches:   1%|▏                    | 3/444 [00:00<01:03,  6.94it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.44it/s]
Translating speeches:   1%|▏                    | 4/444 [00:00<01:17,  5.65it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.21it/s]
Translating speeches:   1%|▏                    | 5/444 [00:00<01:16,  5.76it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.18it/s]
Translating speeches:   1%|▎                    | 6/444 [00:01<01:19,  5.49it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.70it/s]
Translating speeches:   2%|▎                    | 7/444 [00:01<01:19,  5.49it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.32s/it]
Translating speeches:   2%|▍                    | 8/444 [00:02<03:55,  1.85it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.35it/s]
Translating speeches:   2%|▍                    | 9/444 [00:02<03:08,  2.31it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.89it/s]
Translating speeches:   2%|▍                   | 10/444 [00:02<02:38,  2.73it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.46it/s]
Translating speeches:   2%|▍                   | 11/444 [00:03<02:20,  3.08it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.17s/it]
Translating speeches:   3%|▌                   | 12/444 [00:04<04:12,  1.71it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.94it/s]
Translating speeches:   3%|▌                   | 13/444 [00:04<03:18,  2.17it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  1.17it/s]
Translating speeches:   3%|▋                   | 14/444 [00:05<04:09,  1.72it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.39it/s]
Translating speeches:   3%|▋                   | 15/444 [00:05<03:19,  2.15it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.20it/s]
Translating speeches:   4%|▋                   | 16/444 [00:05<02:50,  2.50it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.06it/s]
Translating speeches:   4%|▊                   | 17/444 [00:06<02:25,  2.93it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.24it/s]
Translating speeches:   4%|▊                   | 18/444 [00:06<02:06,  3.36it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.87it/s]
Translating speeches:   4%|▊                   | 19/444 [00:06<01:55,  3.67it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.56it/s]
Translating speeches:   5%|▉                   | 20/444 [00:06<01:49,  3.86it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.59it/s]
Translating speeches:   5%|▉                   | 21/444 [00:06<01:40,  4.21it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.48it/s]
Translating speeches:   5%|▉                   | 22/444 [00:07<01:39,  4.24it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.61it/s]
Translating speeches:   5%|█                   | 23/444 [00:07<01:33,  4.52it/s]
Translating chunks:   0%|                                 | 0/2 [00:00<?, ?it/s]
Translating chunks:  50%|████████████▌            | 1/2 [00:00<00:00,  5.13it/s]
Translating chunks: 100%|█████████████████████████| 2/2 [00:00<00:00,  4.74it/s]
Translating speeches:   5%|█                   | 24/444 [00:07<01:58,  3.55it/s]
Translating chunks:   0%|                                 | 0/9 [00:00<?, ?it/s]
Translating chunks:  11%|██▊                      | 1/9 [00:00<00:01,  4.48it/s]
Translating chunks:  22%|█████▌                   | 2/9 [00:00<00:01,  5.05it/s]
Translating chunks:  33%|████████▎                | 3/9 [00:01<00:04,  1.29it/s]
Translating chunks:  44%|███████████              | 4/9 [00:02<00:02,  1.83it/s]
Translating chunks:  56%|█████████████▉           | 5/9 [00:02<00:01,  2.42it/s]
Translating chunks:  67%|████████████████▋        | 6/9 [00:02<00:01,  2.96it/s]
Translating chunks:  78%|███████████████████▍     | 7/9 [00:02<00:00,  3.30it/s]
Translating chunks:  89%|██████████████████████▏  | 8/9 [00:04<00:00,  1.57it/s]
Translating chunks: 100%|█████████████████████████| 9/9 [00:04<00:00,  2.00it/s]
Translating speeches:   6%|█▏                  | 25/444 [00:11<10:13,  1.46s/it]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.72it/s]
Translating speeches:   6%|█▏                  | 26/444 [00:12<07:35,  1.09s/it]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.62it/s]
Translating speeches:   6%|█▏                  | 27/444 [00:12<05:41,  1.22it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.95it/s]
Translating speeches:   6%|█▎                  | 28/444 [00:12<04:20,  1.60it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.91it/s]
Translating speeches:   7%|█▎                  | 29/444 [00:12<03:28,  1.99it/s]
Translating chunks:   0%|                                 | 0/2 [00:00<?, ?it/s]
Translating chunks:  50%|████████████▌            | 1/2 [00:00<00:00,  4.69it/s]
Translating chunks: 100%|█████████████████████████| 2/2 [00:00<00:00,  4.57it/s]
Translating speeches:   7%|█▎                  | 30/444 [00:13<03:21,  2.06it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  7.33it/s]
Translating speeches:   7%|█▍                  | 31/444 [00:13<02:38,  2.61it/s]
Translating chunks:   0%|                                 | 0/3 [00:00<?, ?it/s]
Translating chunks:  33%|████████▎                | 1/3 [00:00<00:00,  5.12it/s]
Translating chunks:  67%|████████████████▋        | 2/3 [00:01<00:00,  1.20it/s]
Translating chunks: 100%|█████████████████████████| 3/3 [00:01<00:00,  1.79it/s]
Translating speeches:   7%|█▍                  | 32/444 [00:15<05:23,  1.28it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.78it/s]
Translating speeches:   7%|█▍                  | 33/444 [00:15<04:12,  1.63it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.24it/s]
Translating speeches:   8%|█▌                  | 34/444 [00:15<03:20,  2.04it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.88it/s]
Translating speeches:   8%|█▌                  | 35/444 [00:15<02:45,  2.47it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.48it/s]
Translating speeches:   8%|█▌                  | 36/444 [00:15<02:23,  2.84it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.33s/it]
Translating speeches:   8%|█▋                  | 37/444 [00:17<04:23,  1.54it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  1.06it/s]
Translating speeches:   9%|█▋                  | 38/444 [00:18<05:00,  1.35it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  1.23it/s]
Translating speeches:   9%|█▊                  | 39/444 [00:18<05:09,  1.31it/s]
Translating chunks:   0%|                                 | 0/2 [00:00<?, ?it/s]
Translating chunks:  50%|████████████▌            | 1/2 [00:00<00:00,  4.34it/s]
Translating chunks: 100%|█████████████████████████| 2/2 [00:00<00:00,  5.33it/s]
Translating speeches:   9%|█▊                  | 40/444 [00:19<04:24,  1.53it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.28it/s]
Translating speeches:   9%|█▊                  | 41/444 [00:19<03:33,  1.89it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.06it/s]
Translating speeches:   9%|█▉                  | 42/444 [00:19<02:49,  2.37it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.11it/s]
Translating speeches:  10%|█▉                  | 43/444 [00:19<02:22,  2.81it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.85it/s]
Translating speeches:  10%|█▉                  | 44/444 [00:20<02:05,  3.19it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.11it/s]
Translating speeches:  10%|██                  | 45/444 [00:20<01:48,  3.69it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.06it/s]
Translating speeches:  10%|██                  | 46/444 [00:20<01:39,  3.99it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  1.04it/s]
Translating speeches:  11%|██                  | 47/444 [00:21<03:04,  2.15it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.28it/s]
Translating speeches:  11%|██▏                 | 48/444 [00:21<02:32,  2.60it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.98it/s]
Translating speeches:  11%|██▏                 | 49/444 [00:21<02:10,  3.02it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.63it/s]
Translating speeches:  11%|██▎                 | 50/444 [00:22<01:57,  3.34it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.35it/s]
Translating speeches:  11%|██▎                 | 51/444 [00:22<01:45,  3.73it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.43it/s]
Translating speeches:  12%|██▎                 | 52/444 [00:22<01:32,  4.23it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.34it/s]
Translating speeches:  12%|██▍                 | 53/444 [00:22<01:28,  4.43it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  1.18it/s]
Translating speeches:  12%|██▍                 | 54/444 [00:23<02:42,  2.41it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.71it/s]
Translating speeches:  12%|██▍                 | 55/444 [00:23<02:18,  2.80it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.17it/s]
Translating speeches:  13%|██▌                 | 56/444 [00:24<02:00,  3.22it/s]
Translating chunks:   0%|                                 | 0/2 [00:00<?, ?it/s]
Translating chunks:  50%|████████████▌            | 1/2 [00:00<00:00,  5.40it/s]
Translating chunks: 100%|█████████████████████████| 2/2 [00:00<00:00,  4.30it/s]
Translating speeches:  13%|██▌                 | 57/444 [00:24<02:17,  2.82it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.11it/s]
Translating speeches:  13%|██▌                 | 58/444 [00:24<02:04,  3.10it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.90it/s]
Translating speeches:  13%|██▋                 | 59/444 [00:24<01:51,  3.46it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.08it/s]
Translating speeches:  14%|██▋                 | 60/444 [00:25<01:40,  3.81it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.13it/s]
Translating speeches:  14%|██▋                 | 61/444 [00:25<01:33,  4.08it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  2.54it/s]
Translating speeches:  14%|██▊                 | 62/444 [00:25<01:51,  3.42it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.71it/s]
Translating speeches:  14%|██▊                 | 63/444 [00:25<01:38,  3.86it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.19it/s]
Translating speeches:  14%|██▉                 | 64/444 [00:26<01:28,  4.30it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.51it/s]
Translating speeches:  15%|██▉                 | 65/444 [00:26<01:27,  4.31it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.06s/it]
Translating speeches:  15%|██▉                 | 66/444 [00:27<03:02,  2.07it/s]
Translating chunks:   0%|                                 | 0/5 [00:00<?, ?it/s]
Translating chunks:  20%|█████                    | 1/5 [00:00<00:00,  4.77it/s]
Translating chunks:  40%|██████████               | 2/5 [00:00<00:00,  4.54it/s]
Translating chunks:  60%|███████████████          | 3/5 [00:01<00:01,  1.50it/s]
Translating chunks:  80%|████████████████████     | 4/5 [00:01<00:00,  1.99it/s]
Translating chunks: 100%|█████████████████████████| 5/5 [00:02<00:00,  2.44it/s]
Translating speeches:  15%|███                 | 67/444 [00:29<06:09,  1.02it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:01<00:00,  1.01s/it]
Translating speeches:  15%|███                 | 68/444 [00:30<06:13,  1.01it/s]
Translating chunks:   0%|                                 | 0/4 [00:00<?, ?it/s]
Translating chunks:  25%|██████▎                  | 1/4 [00:00<00:00,  5.04it/s]
Translating chunks:  50%|████████████▌            | 2/4 [00:01<00:01,  1.02it/s]
Translating chunks:  75%|██████████████████▊      | 3/4 [00:03<00:01,  1.19s/it]
Translating chunks: 100%|█████████████████████████| 4/4 [00:03<00:00,  1.19it/s]
Translating speeches:  16%|███                 | 69/444 [00:34<10:51,  1.74s/it]
Translating chunks:   0%|                                 | 0/7 [00:00<?, ?it/s]
Translating chunks:  14%|███▌                     | 1/7 [00:00<00:04,  1.23it/s]
Translating chunks:  29%|███████▏                 | 2/7 [00:01<00:02,  2.13it/s]
Translating chunks:  43%|██████████▋              | 3/7 [00:01<00:01,  2.84it/s]
Translating chunks:  57%|██████████████▎          | 4/7 [00:01<00:01,  2.25it/s]
Translating chunks:  71%|█████████████████▊       | 5/7 [00:02<00:00,  2.73it/s]
Translating chunks:  86%|█████████████████████▍   | 6/7 [00:02<00:00,  3.24it/s]
Translating chunks: 100%|█████████████████████████| 7/7 [00:02<00:00,  3.56it/s]
Translating speeches:  16%|███▏                | 70/444 [00:36<12:15,  1.97s/it]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  4.92it/s]
Translating speeches:  16%|███▏                | 71/444 [00:36<08:56,  1.44s/it]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.17it/s]
Translating speeches:  16%|███▏                | 72/444 [00:36<06:37,  1.07s/it]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  5.22it/s]
Translating speeches:  16%|███▎                | 73/444 [00:37<04:59,  1.24it/s]
Translating chunks:   0%|                                 | 0/1 [00:00<?, ?it/s]
Translating chunks: 100%|█████████████████████████| 1/1 [00:00<00:00,  6.91it/s]

✅ Translated segmented speeches and added new column `speech_text_translated`.

,speech_text,speech_text_translated
53689,Het is niet alleen ontzettend verdrietig. De v...,It is not only incredibly sad. The question is...
84500,"Ja precies, de staatsschuld. Hij heeft een pun...","Yes exactly, the national debt. He has made a ..."
69448,U schrijft in de brief ook dat beide rechtbank...,You also write in the letter that both courts ...
58960,Zoals ik in de schriftelijke beantwoording heb...,"As I have indicated in the written answer, it ..."
45377,Dat is de motie-Teunissen over de vlaktaks.,That is the motion - Teunissen about the flat ...

In [28]:
# Define the mapping of label numbers to fallacy types
fallacy_label_mapping = {
    1: "Ad Hominem",
    2: "Appeal to Authority",
    3: "Appeal to Emotion",
    4: "False Cause",
    5: "Slippery Slope",
    6: "Slogans"
}

# Function to classify fallacies in a speech
def classify_fallacies(text):
    """Runs BERT model on a given speech text and returns detected fallacies with proper word reconstruction."""
    
    if not isinstance(text, str) or text.strip() == "":
        return []  # Handle empty input

    chunks = split_into_chunks(text)  # Split long speeches
    predictions = []

    for chunk in chunks:
        try:
            inputs = tokenizer(
                chunk,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )
            inputs = {key: val.to(device) for key, val in inputs.items()}

            with torch.no_grad():
                outputs = model(**inputs)

            logits = outputs.logits
            predicted_labels = torch.argmax(logits, dim=2)  # Get highest probability label

            tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

            # === REBUILD WORDS FROM SUBWORDS ===
            fallacies = []
            current_word = ""
            current_label = None

            for token, label in zip(tokens, predicted_labels[0]):
                word_part = token.replace("##", "")  # Remove subword markers
                
                if token.startswith("##"):  
                    # If it's a continuation subword, append to the current word
                    current_word += word_part
                else:
                    # If it's a new word, store the previous word (if it had a fallacy label)
                    if current_word and current_label is not None:
                        fallacies.append((current_word, fallacy_label_mapping.get(current_label, "Unknown")))

                    # Start a new word
                    current_word = word_part
                    current_label = label.item() if label.item() != 0 else None  # Ignore "O" labels

            # Add last word if it had a label
            if current_word and current_label is not None:
                fallacies.append((current_word, fallacy_label_mapping.get(current_label, "Unknown")))

            predictions.extend(fallacies)

        except Exception as e:
            print(f"⚠️ Error processing chunk: {e}")
            continue  # Skip problematic chunk but continue processing

    return predictions

In [29]:
import nltk
from tqdm import tqdm

nltk.download('punkt')  # Ensure sentence tokenizer is available

# Function to detect fallacies in each sentence separately
def detect_fallacies_in_speech(speech):
    """Splits speech into sentences, detects fallacies, and returns structured output."""
    
    sentences = nltk.sent_tokenize(speech)  # Split speech into sentences
    sentence_fallacies = []  # Store fallacies per sentence
    
    for sentence in sentences:
        fallacies = classify_fallacies(sentence)  # Detect fallacies in this sentence
        
        if fallacies:  # If fallacies are found, format them
            formatted_fallacies = ", ".join([f"{word} → {fallacy}" for word, fallacy in fallacies])
            sentence_fallacies.append(f"{sentence} → {formatted_fallacies}")  # Attach fallacies to the sentence
    
    return " | ".join(sentence_fallacies) if sentence_fallacies else "No fallacy detected"

print("✅ `detect_fallacies_in_speech` function loaded successfully!")

✅ `detect_fallacies_in_speech` function loaded successfully!

[nltk_data] Downloading package punkt to /Users/markus/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [30]:
from tqdm import tqdm  # Ensure tqdm is imported for the progress bar

TEXT_COLUMN = "speech_text_translated"  

# Apply fallacy detection with sentence-level tracking
tqdm.pandas(desc="Detecting fallacies per sentence")
df_sample["fallacy_predictions"] = df_sample[TEXT_COLUMN].progress_apply(detect_fallacies_in_speech)

print("✅ Fallacy detection applied with sentence tracking!")

# Display a few rows with detected fallacies
df_sample[["speech_text_translated", "fallacy_predictions"]].head()

Detecting fallacies per sentence: 100%|███████| 444/444 [28:43<00:00,  3.88s/it]

✅ Fallacy detection applied with sentence tracking!

,speech_text_translated,fallacy_predictions
53689,It is not only incredibly sad. The question is...,The question is of course what consequences th...
84500,"Yes exactly, the national debt. He has made a ...",If you are now going to look at Europe and if ...
69448,You also write in the letter that both courts ...,No fallacy detected
58960,"As I have indicated in the written answer, it ...",I agree with Mrs. Paulusma. → Paulusma → False...
45377,That is the motion - Teunissen about the flat ...,That is the motion - Teunissen about the flat ...

In [31]:
# Define the output file path
OUTPUT_FILE = "fallacy_detection_results.csv"

# Save the dataframe with fallacy predictions
df_sample.to_csv(OUTPUT_FILE, index=False)

print(f"✅ Fallacy detection results saved to {OUTPUT_FILE}!")

✅ Fallacy detection results saved to fallacy_detection_results.csv!